### ISSUE TITLE
Description of the data in the dataset.

### ISSUE THREAD

**Issue by manonthegithub** [mees/calvin#12]
Hello!

I am trying to use the dataset from CALVIN. Would be nice to have a more detailed description of the data format used. I have created the dataset object with `calvin.util.visualize_annotations.load_data` function. To the objects in dataset have `robot_obs` property (vectors of 8 numbers), and 'state_info.robot_obs' (vectors of 15 numbers), 'state_info.scene_obs' (vectors of 24 numbers). As was able to understand from source the 'robot_obs' (vectors of 8) are just preprocessed from 'state_info.robot_obs'. But what do actually those numbers mean? I suppose that first 3 are the coordinates of the gripper (x,y,z), but what are the remaining 5 (probably rotations etc)? And for 'state_info.robot_obs' what are those vectors of 15? 'state_info.scene_obs' (vectors of 24 numbers)?
Could you please give a description somewhere in the README?

**Comment by mees** [comment]
Solved with 94beffd77644aeba06757d06449bfcb86f22117b
