### ISSUE TITLE
Feature Request: Only download language data

### ISSUE THREAD

**Issue by jesbu1** [mees/calvin#27]
Hi,

Is there a way to only download the trajectories that are labeled with language data? I'd like to download the ABC->D dataset, but my use case requires only the trajectories with language data. This would be helpful as the disk space and download time would be only ~1% of what it is now.

Thanks!

**Comment by lukashermann** [comment]
Hey @jesbu1, currently it is not possible to download only the language dataset.
However, the asumption that it would be only 1% of the disk space is also wrong, for an explanation, please refer to this [issue](https://github.com/mees/calvin/issues/23).

**Comment by jesbu1** [comment]
Got it, thanks.
