### ISSUE TITLE
Missing default config: ../datamodule/observation_space/lang_rgb_static.yaml

### ISSUE THREAD

**Issue by mbreuss** [mees/calvin#28]
Hi,

thanks for the great work! I had a very minor isse regarding a missing default config: There is a reference to a non-existing hydra config file in ```calvin/calvin_models/conf/datamodule/default.yaml```:

```yaml
defaults:
  - observation_space: lang_rgb_static
```

However, in ```calvin/calvin_models/conf/datamodule/observation_space``` there does not exist a config file called ```lang_rgb_static.yaml```.

Not sure, if I missed something there. 
Thanks!

**Comment by lukashermann** [comment]
Hey @mbreuss, thank you for noticing this bug, we didn't change the name after renaming the file from `lang_rgb_static` to `lang_rgb_static_abs_act`. I've commited a fix.
