### ISSUE TITLE
Stepping with env.step(action) on playtablesim mutates the input action array.

### ISSUE THREAD

**Issue by jesbu1** [mees/calvin#29]
It seems that when using the PlayTableEnv for RL, the input action is mutated (so our actions being saved to the buffer were incorrect :( ).

I believe that this is due to this line: https://github.com/mees/calvin_env/blob/6e7ceaa6e8dbc0c8582c2ec0c6f7943c68f5ce72/calvin_env/robot/robot.py#L312

Maybe there should be an `np.copy(action)` applied first here?

**Comment by lukashermann** [comment]
Thank you for noticing this bug, I fixed it as you suggested.
