### ISSUE TITLE
How to control panda in joint space ?

### ISSUE THREAD

**Issue by Hymwgk** [mees/calvin#31]
Hi, thanks for sharing this interesting work with us!

I am using the SlideEnv provided in the tutorial Jupiter notebook.  I would like to know how to control the panda robot arm directly in the joint space.
I see that in the "Robot.apply_action(self, action)" function, it seems to use inverse kinematics to translate the gripper pose to the joint angles and only after that to control the robot arm;

I would like the RL agent to output joint angles and gripper action to control the panda motion directly, is there a pre-defined interface for this?
Thanks in advance for your help!

**Comment by lukashermann** [comment]
Hi @Hymwgk, thank you for pointing this out! I added the joint control to `calvin_env`. If you want to use relative joint angles, you can just call the step function of SlideEnv with an 8-tuple (or np array of length 8) containing the 7 relative joint angles and the gripper action. If you want to use absolute joint angles, you have to change  `joint_rel` to `joint_abs` in line 69 of the notebook.

Is this working for you?
