### ISSUE TITLE
Dataset download link returns 404 not found

### ISSUE THREAD

**Issue by notmahi** [mees/calvin#34]
All the links in the dataset download section are broken.

http://calvin.cs.uni-freiburg.de/dataset/calvin_debug_dataset.zip
http://calvin.cs.uni-freiburg.de/dataset/task_D_D.zip
http://calvin.cs.uni-freiburg.de/dataset/task_ABC_D.zip
http://calvin.cs.uni-freiburg.de/dataset/task_ABCD_D.zip

**Comment by mees** [comment]
Thanks for the report! I will investigate this issue and get back to you.

**Comment by mees** [comment]
It should be online again, can you try if it works for you now?

**Comment by notmahi** [comment]
It is online again, thank you :)
