### ISSUE TITLE
Can i train model with 1 laptop gpu?

### ISSUE THREAD

**Issue by datonefaridze** [mees/calvin#44]
Hi, can i train the model with i laptop gpu? when i run the script it outputs the error:
`[1]    26075 segmentation fault (core dumped)`

i have rtx 3060 (laptop version) with 6gb vram

**Comment by mees** [comment]
Hi, you will not be able to train with the original hyperparams, but you can probably try training with a lower batch size. Reducing the sequence length might also be necessary. Remember you will need to change the batch size for both the vision and language datasets. You can override with something like `datamodule.datasets.vision_dataset.batch_size=5 datamodule.datasets.lang_dataset.batch_size=5`
