### ISSUE TITLE
Hardware and time used for training?

### ISSUE THREAD

**Issue by thesofakillers** [mees/calvin#46]
Hi -- thought i'd ask: For your MCIL baseline, could you share which hardware setup you used for training and roughly how long one training run took on that setup?

Is it similar to the [HULC case](https://github.com/lukashermann/hulc/tree/main#hardware-requirements)?

Thank you very much!

**Comment by mees** [comment]
Hi there,
yeah it should be similar. It depends a bit if you train with rollout callbacks switched on or off, as this increases training time, but it should be around 2 days on 8x Nvidia RTX 2080Ti without rollout callbacks.
