### ISSUE TITLE
How to render in a high-resolution mode?

### ISSUE THREAD

**Issue by Ericonaldo** [mees/calvin#55]
Hi I am using CALVIN for my research and I want to show some visualizations in high resolution (200x200 by default). I tried to change the camera size but it won't work. I think there must be solutions as I noticed that the visualization demo shown on the home page is good.

**Comment by 2488583886** [comment]
My email address is [ybfuyujie@gmail.com](mailto:ybfuyujie@gmail.com), thanks so much!

**Comment by mees** [comment]
> Hi I am using CALVIN for my research and I want to show some visualizations in high resolution (200x200 by default). I tried to change the camera size but it won't work. I think there must be solutions as I noticed that the visualization demo shown on the home page is good.

Good question, you can check this cript that we used in the past https://github.com/mees/calvin_env/blob/main/calvin_env/scripts/record_video_icra.py
