### ISSUE TITLE
Dataset downloading issue

### ISSUE THREAD

**Issue by SiyuanHuang95** [mees/calvin#62]
Thanks for your sharing!

1. Finding the wget is too slow, also since that large file is compressed into one file, not robust for the internet temporary issue
2. Possible to hold this dataset with multiple subfiles? And with the Google Drive?
3. Sometimes it rasies with: ERROR 503: Service Unavailable.
4. Would like to know, can we also obtain the more high-quality / high resolution images for this dataset?

**Comment by mees** [comment]
Thanks for pointing this out, I agree that it's not the best way to serve the dataset right now. I will try to look into some alternatives.

**Comment by SiyuanHuang95** [comment]
Thanks for your reply. And how about the HQ images issue, was that possible?

**Comment by mees** [comment]
I don't think so, one would need to re-render the whole splits and host them separately.

**Comment by SiyuanHuang95** [comment]
Okay, or can you provide some script for the HQ images rendering?

**Comment by SiyuanHuang95** [comment]
Hi @lukashermann,

Great thanks for your information. With the current information, I think I am able to render the desired image resolution on my side. Thanks again.
