### ISSUE TITLE
Visualize Language Annotations

### ISSUE THREAD

**Issue by dingjiansw101** [mees/calvin#68]
Thanks the authors for sharing this great work. I met errors when I followed the command for Visualize Language Annotations.
python utils/visualize_annotations.py datamodule.root_data_dir=calvin/dataset/calvin_debug_dataset datamodule/observation_space=lang_rgb_static

In 'datamodule/default': Could not find 'datamodule/observation_space/lang_rgb_static'

Available options in 'datamodule/observation_space':
        all_mods_abs_act
        all_mods_rel_act
        lang_rgb_static_abs_act
        lang_rgb_static_gripper_abs_act
        lang_rgb_static_gripper_rel_act
        lang_rgb_static_rel_act
        lang_rgb_static_robot_scene_abs_act
        lang_rgb_static_tactile_abs_act
        lang_rgb_static_tactile_rel_act
        lang_rgbd_both_abs_act
        lang_rgbd_both_rel_act
        lang_rgbd_static_gripper_rel_act
        lang_rgbd_static_robot_abs_act
        state_only
Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///ibex/user/dingj0b/code/calvin/calvin_models/conf
        provider=hydra-colorlog, path=pkg://hydra_plugins.hydra_colorlog.conf
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

How could I solve this problem?

Look forward to your reply.

Best,
Jian Ding

**Comment by lukashermann** [comment]
Hi @dingjiansw101, thanks for pointing that out, the correct line is 
```
python utils/visualize_annotations.py datamodule.root_data_dir=$CALVIN_ROOT/dataset/task_D_D/ datamodule/observation_space=lang_rgb_static_rel_act
```

Make sure to pull, I also fixed a line in the visualization script.
Cheers
