### ISSUE TITLE
What device did you use to teleoperate the dataset?

### ISSUE THREAD

**Issue by nikepupu** [mees/calvin#7]
I see something like keyboard control in the code. I tried to use the keyboard to control the robot, but it seems to be really difficult to control the robot with the keyboard without any training.

**Comment by mees** [comment]
Hello @nikepupu, we used a HTC Vive VR controller to record the data. Currently, we have not documented how to record teleop data with CALVIN Env, but if there is enough interest, we could do this.

**Comment by nikepupu** [comment]
Are there any resources you can point me to?

**Comment by mees** [comment]
The main for the VR data collection is https://github.com/mees/calvin_env/blob/main/calvin_env/vrdatacollector.py
