### ISSUE TITLE
Dataset Download Issue

### ISSUE THREAD

**Issue by jesnk** [mees/calvin#86]
Currently, the dataset cannot be downloaded. The execution of download_data.sh stops at the following point:

--2024-05-31 16:50:36--  http://calvin.cs.uni-freiburg.de/dataset/task_ABCD_D.zip
Resolving calvin.cs.uni-freiburg.de (calvin.cs.uni-freiburg.de)... 132.230.105.132
Connecting to calvin.cs.uni-freiburg.de (calvin.cs.uni-freiburg.de)|132.230.105.132|:80...

It seems there might be an issue with the server. Is this a known problem? I hope it gets resolved soon. Thank you.

**Comment by mees** [comment]
Hi thanks for the notification, it should be back online now!

**Comment by jesnk** [comment]
Thank you very much! have a good day
