### ISSUE TITLE
Physics of the robot arm is odd

### ISSUE THREAD

**Issue by aliang8** [mees/calvin#9]
I am using the SlideEnv provided in the tutorial jupyter notebook for evaluating a trained RL policy. In some of my rollouts, I noticed in the static camera RGB image that there is an weird piece sticking out of the robot's arm. In the video I attached, that additional piece seems to be manipulating the sliding drawer. I also notice this thing protuding from the arm in the picture of Env B from the paper. Is this supposed to be part of the environment. Thanks!

Link to video: https://drive.google.com/file/d/13P954eWY-stc-Ty4xEhZ2D9HDs6lu_Wb/view?usp=sharing

![image](https://user-images.githubusercontent.com/16139634/148593740-4b741a58-7319-4661-a428-66eb894f44dd.png)

**Comment by mees** [comment]
Thanks for trying out CALVIN @aliang8 !
Wow, that's a definitely cool novel way of sliding the drawer we have not observed before! :open_mouth:
The floating block you mention is the, not so realistically depicted, gripper camera. If you don't need the gripper camera you can remove it or allow collisions for it here https://github.com/mees/calvin_env/blob/main/data/franka_panda/panda.urdf#L346

**Comment by lukashermann** [comment]
@mees I think we should disable collisions completely for the gripper camera, what do you think?

**Comment by mees** [comment]
@lukashermann I agree.

**Comment by lukashermann** [comment]
Collisions are now disabled.
