### ISSUE TITLE
ModuleNotFoundError: No module named 'calvin_env'

### ISSUE THREAD

**Issue by 1425629616** [mees/calvin#95]
Hi, I am tring to run this:
python evaluation/evaluate_policy.py --dataset_path /root/autodl-tmp/calvin/dataset/calvin_debug_dataset --custom_model
to test my own model, but get error as follow, and I don't know what cause it:

Traceback (most recent call last):
  File "evaluation/evaluate_policy.py", line 34, in <module>
    from calvin_env.envs.play_table_env import get_env
ModuleNotFoundError: No module named 'calvin_env'

Thank you for taking the time to read my question amidst your busy schedule.

**Comment by liaoyuanlei** [comment]
I have encountered the same problem. May I ask how you solved it?
